### ISSUE TITLE
Rainbow Brackets is disabling IntelliJ's Semantic Highlighting

### ISSUE THREAD

**Issue by mjparme** [izhangzhihao/intellij-rainbow-brackets#2590]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages

Java

## Expected Behavior

Rainbow Brackets should not turn off IntelliJ's Semantic Highlighting. 

## Current Behavior

If Rainbow Brackets is enabled everytime IntelliJ starts Rainbow Brackets disables IntelliJ's Semantic Highlighting.

## Possible Solution

The Rainbow Brackets plugin has a setting on its setting screen something like "Will enabled IntelliJ's semantic highlighting". I selected that option thinking that might fix this behavior but selecting that had no effect. Semantic highlighting was still turned off.

So my current solution is to disable the Rainbow Brackets plugin. This fixes the problem. I miss it but semantic highlighting is more important to me and since I can either have Rainbow Brackets or semantic highlighting I went with semantic highlighting.

## Code snippet for reproduce (for bugs)

N/A

## Your Environment

* Plugin version: 2023.1.2
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
IntelliJ IDEA 2023.1 EAP (Ultimate Edition)
Build #IU-231.6471.13, built on February 3, 2023
Licensed to IntelliJ IDEA EAP user: mjparme
Expiration date: March 5, 2023
Runtime version: 17.0.6+10-b785.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    com.jetbrains.darkPurpleTheme (1.3)
    IdeaVIM (2.1.0)
    org.jetbrains.plugins.go-template (231.6471.1)
    org.jetbrains.plugins.go (231.6471.13)
    org.jetbrains.idea.grammar (2022.3)
    InnerBuilder (1.3.0)
    org.mapstruct.intellij (1.4.0)
    org.jetbrains.compose.desktop.ide (1.3.0)

Kotlin: 231-1.8.0-release-345-IJ6471.13
```

Note that the same problem occurs on all 2022.x versions as well.

**Comment by mjparme** [comment]
I wonder if your fix for https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2551 broke this?

**Comment by izhangzhihao** [comment]
Yes, it is already fixed.

**Comment by izhangzhihao** [comment]
If you still found this issue happens, please reply to this issue or create a new one.

**Comment by mjparme** [comment]
Can you tell me which version of the plugin no longer disables IntelliJ's semantic highlighting? As far as I can tell I have the most recent version and it still occurs.

**Comment by intellij-rainbow-brackets** [comment]
Can you tell me what is most recent version?

发件人: Michael Parmeley ***@***.***>
日期: 星期二, 2023年2月7日 下午1:57
收件人: izhangzhihao/intellij-rainbow-brackets ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [izhangzhihao/intellij-rainbow-brackets] Rainbow Brackets is disabling IntelliJ's Semantic Highlighting (Issue #2590)

Can you tell me which version of the plugin no longer disables IntelliJ's semantic highlighting? As far as I can tell I have the most recent version and it still occurs.

―

**Comment by mjparme** [comment]
I have `2023.1.2` installed (although I currently have it disabled because I really need semantic highlighting)

**Comment by izhangzhihao** [comment]
Check the LATEST version here: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions

**Comment by mjparme** [comment]
Thank you. I will give that one a try tomorrow.

**Comment by kiroshmarin** [comment]
Semantic highlighting and raindow work together with rainbow version 6.26 (in idea 2023.2)
