### ISSUE TITLE
Brackets in MXML attribute value

### ISSUE THREAD

**Issue by rs7** [izhangzhihao/intellij-rainbow-brackets#54]
MXML language

Wrong hightlighting
![screenshot_274](https://user-images.githubusercontent.com/971343/39703871-d1d55f8e-5233-11e8-840f-5f92e318730c.png)
```
<?xml version="1.0"?>
<mx:Box
    xmlns:mx="http://www.adobe.com/2006/mxml"
    width="{800}"
    height="{600}"
/>
```
Plugin version: 5.2
```
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 30, 2018
Windows 7 6.1
```

**Comment by izhangzhihao** [comment]
Are you using the "MXML Design Preview" plugin?

**Comment by izhangzhihao** [comment]
It seems fixed in the [new release](https://github.com/izhangzhihao/intellij-rainbow-brackets/releases/tag/5.4)

**Comment by rs7** [comment]
No, I do not use "MXML Design Preview"
Unfortunately, new release not fixed this

![screenshot_275](https://user-images.githubusercontent.com/971343/39711989-a8efaefe-524b-11e8-8757-e9f5ac0c484f.png)

**Comment by izhangzhihao** [comment]
What plugs are you using at the same time, cause I can't reproduce this in my env.

**Comment by rs7** [comment]
General plug
```
Flash/Flex Support 
Version: 173.4674.33
```
and that custom plugs in my ide
```
.ignore
Batch Scripts Support 
CamelCase 
Erlang 
Handlebars/Mustache 
JSON Viewer 
NodeJS 
Rainbow Brackets 
Vue.JS 
R Language Support
```

**Comment by izhangzhihao** [comment]
Strange behaviour ...

**Comment by kyle-mcknight** [comment]
I am also getting this same behavior even in the newest version as of 5.9.1.

I get different results if there is a space after the leading bracket or not. 

![Rainbow Brackets Error](http://45.55.0.109/images/intellij-rainbow-brackets.png)

**Comment by izhangzhihao** [comment]
Now `mxml` files won't be handled by this plugin.
